//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by Luiz Vasconcellos on 15/08/24.
//

import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              title: "Miami Villa",
              ownerUid: NSUUID().uuidString,
              ownerName: "Maria João",
              ownerImageUrl: "profile",
              numberOfBedrooms: 4,
              numberOfBeds: 4,
              numberOfBethrooms: 3,
              numberOfGuests: 6,
              pricePerNight: 345,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              address: "123 Main st",
              city: "Miami",
              state: "Florida",
              rating: 4.48,
              numberOfReviews: 107,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmsystem, .balcony, .laundry, .tv, .pool],
              type: .villa),
        .init(id: NSUUID().uuidString,
              title: "Miami Beach House",
              ownerUid: NSUUID().uuidString,
              ownerName: "Mary Jhonson",
              ownerImageUrl: "profile",
              numberOfBedrooms: 4,
              numberOfBeds: 4,
              numberOfBethrooms: 3,
              numberOfGuests: 6,
              pricePerNight: 678,
              latitude: 25.7706,
              longitude: -80.1340,
              imageURLs: ["image-4", "image-5", "image-6"],
              address: "123 Main st",
              city: "Miami",
              state: "Florida",
              rating: 4.97, 
              numberOfReviews: 57,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmsystem, .office, .kitchen, .laundry, .tv, .pool],
              type: .house),
        .init(id: NSUUID().uuidString,
              title: "Beautiful Miami apartment in downtown Brickell",
              ownerUid: NSUUID().uuidString,
              ownerName: "Silvia Jhonson",
              ownerImageUrl: "profile",
              numberOfBedrooms: 4,
              numberOfBeds: 4,
              numberOfBethrooms: 3,
              numberOfGuests: 6,
              pricePerNight: 278,
              latitude: 25.7650,
              longitude: -80.1936,
              imageURLs: ["image-5", "image-6", "image-7"],
              address: "123 Main st",
              city: "Miami",
              state: "Florida",
              rating: 4.53, 
              numberOfReviews: 23,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmsystem, .balcony, .kitchen, .tv],
              type: .apartment),
        .init(id: NSUUID().uuidString,
              title: "Hollywood Amazing House",
              ownerUid: NSUUID().uuidString,
              ownerName: "Mary Jhonson",
              ownerImageUrl: "profile",
              numberOfBedrooms: 10,
              numberOfBeds: 16,
              numberOfBethrooms: 3,
              numberOfGuests: 14,
              pricePerNight: 897,
              latitude: 34.0549,
              longitude: -118.2426,
              imageURLs: ["image-4", "image-5", "image-6"],
              address: "123 Main st",
              city: "Los Angeles",
              state: "California",
              rating: 4.99, 
              numberOfReviews: 89,
              features: [.selfCheckin, .superHost],
              amenities: [.tv, .balcony, .wifi, .alarmsystem, .office, .kitchen, .laundry, .pool],
              type: .house),
    ]
}
